/**
 * Images live in Vercel Blob and are resized on request by Vercel Image
 * Optimization (/_vercel/image), at the widths in IMAGE_WIDTHS.
 */
import dimensions from '../data/image-dimensions.json';
import { IMAGE_WIDTHS } from './ids.mjs';

const QUALITY = 75;

/** Resized image URL. In `astro dev` the original is used, because the optimizer only exists on Vercel. */
export function imageUrl(src: string, width: number): string {
  if (import.meta.env.DEV) return src;
  return `/_vercel/image?url=${encodeURIComponent(src)}&w=${width}&q=${QUALITY}`;
}

export function imageSrcset(src: string): string | undefined {
  if (import.meta.env.DEV) return undefined;
  return IMAGE_WIDTHS.map((w) => `${imageUrl(src, w)} ${w}w`).join(', ');
}

/**
 * Intrinsic size of an image, so the browser can reserve space before it loads
 * and the page doesn't jump. Generated by `npm run images:dimensions`.
 */
export function imageSize(src: string): { width: number; height: number } | undefined {
  return (dimensions as Record<string, { width: number; height: number }>)[src];
}
