//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  artworks: Artworks;
  artworksConnection: ArtworksConnection;
  works: Works;
  worksConnection: WorksConnection;
  homepage: Homepage;
  homepageConnection: HomepageConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryArtworksArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryArtworksConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ArtworksFilter>;
};


export type QueryWorksArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryWorksConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<WorksFilter>;
};


export type QueryHomepageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomepageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomepageFilter>;
};

export type DocumentFilter = {
  artworks?: InputMaybe<ArtworksFilter>;
  works?: InputMaybe<WorksFilter>;
  homepage?: InputMaybe<HomepageFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Artworks | Works | Homepage | Folder;

export type Artworks = Node & Document & {
  __typename?: 'Artworks';
  title: Scalars['String']['output'];
  image: Scalars['String']['output'];
  medium?: Maybe<Scalars['String']['output']>;
  dimensions?: Maybe<Scalars['String']['output']>;
  year?: Maybe<Scalars['Float']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type ArtworksFilter = {
  title?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  medium?: InputMaybe<StringFilter>;
  dimensions?: InputMaybe<StringFilter>;
  year?: InputMaybe<NumberFilter>;
  description?: InputMaybe<StringFilter>;
};

export type ArtworksConnectionEdges = {
  __typename?: 'ArtworksConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Artworks>;
};

export type ArtworksConnection = Connection & {
  __typename?: 'ArtworksConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ArtworksConnectionEdges>>>;
};

export type Works = Node & Document & {
  __typename?: 'Works';
  title: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  subtitle?: Maybe<Scalars['String']['output']>;
  year?: Maybe<Scalars['Float']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  coverImage: Scalars['String']['output'];
  artworks?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  order?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type WorksFilter = {
  title?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  year?: InputMaybe<NumberFilter>;
  description?: InputMaybe<StringFilter>;
  coverImage?: InputMaybe<ImageFilter>;
  artworks?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type WorksConnectionEdges = {
  __typename?: 'WorksConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Works>;
};

export type WorksConnection = Connection & {
  __typename?: 'WorksConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<WorksConnectionEdges>>>;
};

export type HomepageImages = {
  __typename?: 'HomepageImages';
  image: Scalars['String']['output'];
  alt?: Maybe<Scalars['String']['output']>;
  workSlug?: Maybe<Scalars['String']['output']>;
  artworkId?: Maybe<Scalars['String']['output']>;
};

export type Homepage = Node & Document & {
  __typename?: 'Homepage';
  images?: Maybe<Array<Maybe<HomepageImages>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type HomepageImagesFilter = {
  image?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
  workSlug?: InputMaybe<StringFilter>;
  artworkId?: InputMaybe<StringFilter>;
};

export type HomepageFilter = {
  images?: InputMaybe<HomepageImagesFilter>;
};

export type HomepageConnectionEdges = {
  __typename?: 'HomepageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Homepage>;
};

export type HomepageConnection = Connection & {
  __typename?: 'HomepageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomepageConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateArtworks: Artworks;
  createArtworks: Artworks;
  updateWorks: Works;
  createWorks: Works;
  updateHomepage: Homepage;
  createHomepage: Homepage;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateArtworksArgs = {
  relativePath: Scalars['String']['input'];
  params: ArtworksMutation;
};


export type MutationCreateArtworksArgs = {
  relativePath: Scalars['String']['input'];
  params: ArtworksMutation;
};


export type MutationUpdateWorksArgs = {
  relativePath: Scalars['String']['input'];
  params: WorksMutation;
};


export type MutationCreateWorksArgs = {
  relativePath: Scalars['String']['input'];
  params: WorksMutation;
};


export type MutationUpdateHomepageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageMutation;
};


export type MutationCreateHomepageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageMutation;
};

export type DocumentUpdateMutation = {
  artworks?: InputMaybe<ArtworksMutation>;
  works?: InputMaybe<WorksMutation>;
  homepage?: InputMaybe<HomepageMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  artworks?: InputMaybe<ArtworksMutation>;
  works?: InputMaybe<WorksMutation>;
  homepage?: InputMaybe<HomepageMutation>;
};

export type ArtworksMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  medium?: InputMaybe<Scalars['String']['input']>;
  dimensions?: InputMaybe<Scalars['String']['input']>;
  year?: InputMaybe<Scalars['Float']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type WorksMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  year?: InputMaybe<Scalars['Float']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  coverImage?: InputMaybe<Scalars['String']['input']>;
  artworks?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  order?: InputMaybe<Scalars['Float']['input']>;
};

export type HomepageImagesMutation = {
  image?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
  workSlug?: InputMaybe<Scalars['String']['input']>;
  artworkId?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageMutation = {
  images?: InputMaybe<Array<InputMaybe<HomepageImagesMutation>>>;
};

export type ArtworksPartsFragment = { __typename: 'Artworks', title: string, image: string, medium?: string | null, dimensions?: string | null, year?: number | null, description?: string | null };

export type WorksPartsFragment = { __typename: 'Works', title: string, slug: string, subtitle?: string | null, year?: number | null, description?: string | null, coverImage: string, artworks?: Array<string | null> | null, order?: number | null };

export type HomepagePartsFragment = { __typename: 'Homepage', images?: Array<{ __typename: 'HomepageImages', image: string, alt?: string | null, workSlug?: string | null, artworkId?: string | null } | null> | null };

export type ArtworksQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ArtworksQuery = { __typename?: 'Query', artworks: { __typename: 'Artworks', id: string, title: string, image: string, medium?: string | null, dimensions?: string | null, year?: number | null, description?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ArtworksConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ArtworksFilter>;
}>;


export type ArtworksConnectionQuery = { __typename?: 'Query', artworksConnection: { __typename?: 'ArtworksConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ArtworksConnectionEdges', cursor: string, node?: { __typename: 'Artworks', id: string, title: string, image: string, medium?: string | null, dimensions?: string | null, year?: number | null, description?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type WorksQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type WorksQuery = { __typename?: 'Query', works: { __typename: 'Works', id: string, title: string, slug: string, subtitle?: string | null, year?: number | null, description?: string | null, coverImage: string, artworks?: Array<string | null> | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type WorksConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<WorksFilter>;
}>;


export type WorksConnectionQuery = { __typename?: 'Query', worksConnection: { __typename?: 'WorksConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'WorksConnectionEdges', cursor: string, node?: { __typename: 'Works', id: string, title: string, slug: string, subtitle?: string | null, year?: number | null, description?: string | null, coverImage: string, artworks?: Array<string | null> | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type HomepageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomepageQuery = { __typename?: 'Query', homepage: { __typename: 'Homepage', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, images?: Array<{ __typename: 'HomepageImages', image: string, alt?: string | null, workSlug?: string | null, artworkId?: string | null } | null> | null } };

export type HomepageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomepageFilter>;
}>;


export type HomepageConnectionQuery = { __typename?: 'Query', homepageConnection: { __typename?: 'HomepageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomepageConnectionEdges', cursor: string, node?: { __typename: 'Homepage', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, images?: Array<{ __typename: 'HomepageImages', image: string, alt?: string | null, workSlug?: string | null, artworkId?: string | null } | null> | null } | null } | null> | null } };

export const ArtworksPartsFragmentDoc = gql`
    fragment ArtworksParts on Artworks {
  __typename
  title
  image
  medium
  dimensions
  year
  description
}
    `;
export const WorksPartsFragmentDoc = gql`
    fragment WorksParts on Works {
  __typename
  title
  slug
  subtitle
  year
  description
  coverImage
  artworks
  order
}
    `;
export const HomepagePartsFragmentDoc = gql`
    fragment HomepageParts on Homepage {
  __typename
  images {
    __typename
    image
    alt
    workSlug
    artworkId
  }
}
    `;
export const ArtworksDocument = gql`
    query artworks($relativePath: String!) {
  artworks(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ArtworksParts
  }
}
    ${ArtworksPartsFragmentDoc}`;
export const ArtworksConnectionDocument = gql`
    query artworksConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ArtworksFilter) {
  artworksConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ArtworksParts
      }
    }
  }
}
    ${ArtworksPartsFragmentDoc}`;
export const WorksDocument = gql`
    query works($relativePath: String!) {
  works(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...WorksParts
  }
}
    ${WorksPartsFragmentDoc}`;
export const WorksConnectionDocument = gql`
    query worksConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: WorksFilter) {
  worksConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...WorksParts
      }
    }
  }
}
    ${WorksPartsFragmentDoc}`;
export const HomepageDocument = gql`
    query homepage($relativePath: String!) {
  homepage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomepageParts
  }
}
    ${HomepagePartsFragmentDoc}`;
export const HomepageConnectionDocument = gql`
    query homepageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomepageFilter) {
  homepageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomepageParts
      }
    }
  }
}
    ${HomepagePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      artworks(variables: ArtworksQueryVariables, options?: C): Promise<{data: ArtworksQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArtworksQueryVariables, query: string}> {
        return requester<{data: ArtworksQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArtworksQueryVariables, query: string}, ArtworksQueryVariables>(ArtworksDocument, variables, options);
      },
    artworksConnection(variables?: ArtworksConnectionQueryVariables, options?: C): Promise<{data: ArtworksConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArtworksConnectionQueryVariables, query: string}> {
        return requester<{data: ArtworksConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArtworksConnectionQueryVariables, query: string}, ArtworksConnectionQueryVariables>(ArtworksConnectionDocument, variables, options);
      },
    works(variables: WorksQueryVariables, options?: C): Promise<{data: WorksQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WorksQueryVariables, query: string}> {
        return requester<{data: WorksQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WorksQueryVariables, query: string}, WorksQueryVariables>(WorksDocument, variables, options);
      },
    worksConnection(variables?: WorksConnectionQueryVariables, options?: C): Promise<{data: WorksConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WorksConnectionQueryVariables, query: string}> {
        return requester<{data: WorksConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WorksConnectionQueryVariables, query: string}, WorksConnectionQueryVariables>(WorksConnectionDocument, variables, options);
      },
    homepage(variables: HomepageQueryVariables, options?: C): Promise<{data: HomepageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageQueryVariables, query: string}> {
        return requester<{data: HomepageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageQueryVariables, query: string}, HomepageQueryVariables>(HomepageDocument, variables, options);
      },
    homepageConnection(variables?: HomepageConnectionQueryVariables, options?: C): Promise<{data: HomepageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageConnectionQueryVariables, query: string}> {
        return requester<{data: HomepageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageConnectionQueryVariables, query: string}, HomepageConnectionQueryVariables>(HomepageConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.0/content/e32ea9f6-3abd-4a6b-8569-fd954eeb2efb/github/master",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  